import 'package:phosphor_flutter/phosphor_flutter.dart';

final icons = {
  'acorn': PhosphorIcons.acorn(),
  'address book': PhosphorIcons.addressBook(),
  'address book tabs': PhosphorIcons.addressBookTabs(),
  'air traffic control': PhosphorIcons.airTrafficControl(),
  'airplane': PhosphorIcons.airplane(),
  'airplane in flight': PhosphorIcons.airplaneInFlight(),
  'airplane landing': PhosphorIcons.airplaneLanding(),
  'airplane takeoff': PhosphorIcons.airplaneTakeoff(),
  'airplane taxiing': PhosphorIcons.airplaneTaxiing(),
  'airplane tilt': PhosphorIcons.airplaneTilt(),
  'airplay': PhosphorIcons.airplay(),
  'alarm': PhosphorIcons.alarm(),
  'alien': PhosphorIcons.alien(),
  'align bottom': PhosphorIcons.alignBottom(),
  'align bottom simple': PhosphorIcons.alignBottomSimple(),
  'align center horizontal': PhosphorIcons.alignCenterHorizontal(),
  'align center horizontal simple': PhosphorIcons.alignCenterHorizontalSimple(),
  'align center vertical': PhosphorIcons.alignCenterVertical(),
  'align center vertical simple': PhosphorIcons.alignCenterVerticalSimple(),
  'align left': PhosphorIcons.alignLeft(),
  'align left simple': PhosphorIcons.alignLeftSimple(),
  'align right': PhosphorIcons.alignRight(),
  'align right simple': PhosphorIcons.alignRightSimple(),
  'align top': PhosphorIcons.alignTop(),
  'align top simple': PhosphorIcons.alignTopSimple(),
  'amazon logo': PhosphorIcons.amazonLogo(),
  'ambulance': PhosphorIcons.ambulance(),
  'anchor': PhosphorIcons.anchor(),
  'anchor simple': PhosphorIcons.anchorSimple(),
  'android logo': PhosphorIcons.androidLogo(),
  'angle': PhosphorIcons.angle(),
  'angular logo': PhosphorIcons.angularLogo(),
  'aperture': PhosphorIcons.aperture(),
  'app store logo': PhosphorIcons.appStoreLogo(),
  'app window': PhosphorIcons.appWindow(),
  'apple logo': PhosphorIcons.appleLogo(),
  'apple podcasts logo': PhosphorIcons.applePodcastsLogo(),
  'approximate equals': PhosphorIcons.approximateEquals(),
  'archive': PhosphorIcons.archive(),
  'armchair': PhosphorIcons.armchair(),
  'arrow arc left': PhosphorIcons.arrowArcLeft(),
  'arrow arc right': PhosphorIcons.arrowArcRight(),
  'arrow bend double up left': PhosphorIcons.arrowBendDoubleUpLeft(),
  'arrow bend double up right': PhosphorIcons.arrowBendDoubleUpRight(),
  'arrow bend down left': PhosphorIcons.arrowBendDownLeft(),
  'arrow bend down right': PhosphorIcons.arrowBendDownRight(),
  'arrow bend left down': PhosphorIcons.arrowBendLeftDown(),
  'arrow bend left up': PhosphorIcons.arrowBendLeftUp(),
  'arrow bend right down': PhosphorIcons.arrowBendRightDown(),
  'arrow bend right up': PhosphorIcons.arrowBendRightUp(),
  'arrow bend up left': PhosphorIcons.arrowBendUpLeft(),
  'arrow bend up right': PhosphorIcons.arrowBendUpRight(),
  'arrow circle down': PhosphorIcons.arrowCircleDown(),
  'arrow circle down left': PhosphorIcons.arrowCircleDownLeft(),
  'arrow circle down right': PhosphorIcons.arrowCircleDownRight(),
  'arrow circle left': PhosphorIcons.arrowCircleLeft(),
  'arrow circle right': PhosphorIcons.arrowCircleRight(),
  'arrow circle up': PhosphorIcons.arrowCircleUp(),
  'arrow circle up left': PhosphorIcons.arrowCircleUpLeft(),
  'arrow circle up right': PhosphorIcons.arrowCircleUpRight(),
  'arrow clockwise': PhosphorIcons.arrowClockwise(),
  'arrow counter clockwise': PhosphorIcons.arrowCounterClockwise(),
  'arrow down': PhosphorIcons.arrowDown(),
  'arrow down left': PhosphorIcons.arrowDownLeft(),
  'arrow down right': PhosphorIcons.arrowDownRight(),
  'arrow elbow down left': PhosphorIcons.arrowElbowDownLeft(),
  'arrow elbow down right': PhosphorIcons.arrowElbowDownRight(),
  'arrow elbow left': PhosphorIcons.arrowElbowLeft(),
  'arrow elbow left down': PhosphorIcons.arrowElbowLeftDown(),
  'arrow elbow left up': PhosphorIcons.arrowElbowLeftUp(),
  'arrow elbow right': PhosphorIcons.arrowElbowRight(),
  'arrow elbow right down': PhosphorIcons.arrowElbowRightDown(),
  'arrow elbow right up': PhosphorIcons.arrowElbowRightUp(),
  'arrow elbow up left': PhosphorIcons.arrowElbowUpLeft(),
  'arrow elbow up right': PhosphorIcons.arrowElbowUpRight(),
  'arrow fat down': PhosphorIcons.arrowFatDown(),
  'arrow fat left': PhosphorIcons.arrowFatLeft(),
  'arrow fat line down': PhosphorIcons.arrowFatLineDown(),
  'arrow fat line left': PhosphorIcons.arrowFatLineLeft(),
  'arrow fat line right': PhosphorIcons.arrowFatLineRight(),
  'arrow fat line up': PhosphorIcons.arrowFatLineUp(),
  'arrow fat lines down': PhosphorIcons.arrowFatLinesDown(),
  'arrow fat lines left': PhosphorIcons.arrowFatLinesLeft(),
  'arrow fat lines right': PhosphorIcons.arrowFatLinesRight(),
  'arrow fat lines up': PhosphorIcons.arrowFatLinesUp(),
  'arrow fat right': PhosphorIcons.arrowFatRight(),
  'arrow fat up': PhosphorIcons.arrowFatUp(),
  'arrow left': PhosphorIcons.arrowLeft(),
  'arrow line down': PhosphorIcons.arrowLineDown(),
  'arrow line down left': PhosphorIcons.arrowLineDownLeft(),
  'arrow line down right': PhosphorIcons.arrowLineDownRight(),
  'arrow line left': PhosphorIcons.arrowLineLeft(),
  'arrow line right': PhosphorIcons.arrowLineRight(),
  'arrow line up': PhosphorIcons.arrowLineUp(),
  'arrow line up left': PhosphorIcons.arrowLineUpLeft(),
  'arrow line up right': PhosphorIcons.arrowLineUpRight(),
  'arrow right': PhosphorIcons.arrowRight(),
  'arrow square down': PhosphorIcons.arrowSquareDown(),
  'arrow square down left': PhosphorIcons.arrowSquareDownLeft(),
  'arrow square down right': PhosphorIcons.arrowSquareDownRight(),
  'arrow square in': PhosphorIcons.arrowSquareIn(),
  'arrow square left': PhosphorIcons.arrowSquareLeft(),
  'arrow square out': PhosphorIcons.arrowSquareOut(),
  'arrow square right': PhosphorIcons.arrowSquareRight(),
  'arrow square up': PhosphorIcons.arrowSquareUp(),
  'arrow square up left': PhosphorIcons.arrowSquareUpLeft(),
  'arrow square up right': PhosphorIcons.arrowSquareUpRight(),
  'arrow u down left': PhosphorIcons.arrowUDownLeft(),
  'arrow u down right': PhosphorIcons.arrowUDownRight(),
  'arrow u left down': PhosphorIcons.arrowULeftDown(),
  'arrow u left up': PhosphorIcons.arrowULeftUp(),
  'arrow u right down': PhosphorIcons.arrowURightDown(),
  'arrow u right up': PhosphorIcons.arrowURightUp(),
  'arrow u up left': PhosphorIcons.arrowUUpLeft(),
  'arrow u up right': PhosphorIcons.arrowUUpRight(),
  'arrow up': PhosphorIcons.arrowUp(),
  'arrow up left': PhosphorIcons.arrowUpLeft(),
  'arrow up right': PhosphorIcons.arrowUpRight(),
  'arrows clockwise': PhosphorIcons.arrowsClockwise(),
  'arrows counter clockwise': PhosphorIcons.arrowsCounterClockwise(),
  'arrows down up': PhosphorIcons.arrowsDownUp(),
  'arrows horizontal': PhosphorIcons.arrowsHorizontal(),
  'arrows in': PhosphorIcons.arrowsIn(),
  'arrows in cardinal': PhosphorIcons.arrowsInCardinal(),
  'arrows in line horizontal': PhosphorIcons.arrowsInLineHorizontal(),
  'arrows in line vertical': PhosphorIcons.arrowsInLineVertical(),
  'arrows in simple': PhosphorIcons.arrowsInSimple(),
  'arrows left right': PhosphorIcons.arrowsLeftRight(),
  'arrows merge': PhosphorIcons.arrowsMerge(),
  'arrows out': PhosphorIcons.arrowsOut(),
  'arrows out cardinal': PhosphorIcons.arrowsOutCardinal(),
  'arrows out line horizontal': PhosphorIcons.arrowsOutLineHorizontal(),
  'arrows out line vertical': PhosphorIcons.arrowsOutLineVertical(),
  'arrows out simple': PhosphorIcons.arrowsOutSimple(),
  'arrows split': PhosphorIcons.arrowsSplit(),
  'arrows vertical': PhosphorIcons.arrowsVertical(),
  'article': PhosphorIcons.article(),
  'article medium': PhosphorIcons.articleMedium(),
  'article ny times': PhosphorIcons.articleNyTimes(),
  'asclepius': PhosphorIcons.asclepius(),
  'asterisk': PhosphorIcons.asterisk(),
  'asterisk simple': PhosphorIcons.asteriskSimple(),
  'at': PhosphorIcons.at(),
  'atom': PhosphorIcons.atom(),
  'avocado': PhosphorIcons.avocado(),
  'axe': PhosphorIcons.axe(),
  'baby': PhosphorIcons.baby(),
  'baby carriage': PhosphorIcons.babyCarriage(),
  'backpack': PhosphorIcons.backpack(),
  'backspace': PhosphorIcons.backspace(),
  'bag': PhosphorIcons.bag(),
  'bag simple': PhosphorIcons.bagSimple(),
  'balloon': PhosphorIcons.balloon(),
  'bandaids': PhosphorIcons.bandaids(),
  'bank': PhosphorIcons.bank(),
  'barbell': PhosphorIcons.barbell(),
  'barcode': PhosphorIcons.barcode(),
  'barn': PhosphorIcons.barn(),
  'barricade': PhosphorIcons.barricade(),
  'baseball': PhosphorIcons.baseball(),
  'baseball cap': PhosphorIcons.baseballCap(),
  'baseball helmet': PhosphorIcons.baseballHelmet(),
  'basket': PhosphorIcons.basket(),
  'basketball': PhosphorIcons.basketball(),
  'bathtub': PhosphorIcons.bathtub(),
  'battery charging': PhosphorIcons.batteryCharging(),
  'battery charging vertical': PhosphorIcons.batteryChargingVertical(),
  'battery empty': PhosphorIcons.batteryEmpty(),
  'battery full': PhosphorIcons.batteryFull(),
  'battery high': PhosphorIcons.batteryHigh(),
  'battery low': PhosphorIcons.batteryLow(),
  'battery medium': PhosphorIcons.batteryMedium(),
  'battery plus': PhosphorIcons.batteryPlus(),
  'battery plus vertical': PhosphorIcons.batteryPlusVertical(),
  'battery vertical empty': PhosphorIcons.batteryVerticalEmpty(),
  'battery vertical full': PhosphorIcons.batteryVerticalFull(),
  'battery vertical high': PhosphorIcons.batteryVerticalHigh(),
  'battery vertical low': PhosphorIcons.batteryVerticalLow(),
  'battery vertical medium': PhosphorIcons.batteryVerticalMedium(),
  'battery warning': PhosphorIcons.batteryWarning(),
  'battery warning vertical': PhosphorIcons.batteryWarningVertical(),
  'beach ball': PhosphorIcons.beachBall(),
  'beanie': PhosphorIcons.beanie(),
  'bed': PhosphorIcons.bed(),
  'beer bottle': PhosphorIcons.beerBottle(),
  'beer stein': PhosphorIcons.beerStein(),
  'behance logo': PhosphorIcons.behanceLogo(),
  'bell': PhosphorIcons.bell(),
  'bell ringing': PhosphorIcons.bellRinging(),
  'bell simple': PhosphorIcons.bellSimple(),
  'bell simple ringing': PhosphorIcons.bellSimpleRinging(),
  'bell simple slash': PhosphorIcons.bellSimpleSlash(),
  'bell simple z': PhosphorIcons.bellSimpleZ(),
  'bell slash': PhosphorIcons.bellSlash(),
  'bell z': PhosphorIcons.bellZ(),
  'belt': PhosphorIcons.belt(),
  'bezier curve': PhosphorIcons.bezierCurve(),
  'bicycle': PhosphorIcons.bicycle(),
  'binary': PhosphorIcons.binary(),
  'binoculars': PhosphorIcons.binoculars(),
  'biohazard': PhosphorIcons.biohazard(),
  'bird': PhosphorIcons.bird(),
  'blueprint': PhosphorIcons.blueprint(),
  'bluetooth': PhosphorIcons.bluetooth(),
  'bluetooth connected': PhosphorIcons.bluetoothConnected(),
  'bluetooth slash': PhosphorIcons.bluetoothSlash(),
  'bluetooth x': PhosphorIcons.bluetoothX(),
  'boat': PhosphorIcons.boat(),
  'bomb': PhosphorIcons.bomb(),
  'bone': PhosphorIcons.bone(),
  'book': PhosphorIcons.book(),
  'book bookmark': PhosphorIcons.bookBookmark(),
  'book open': PhosphorIcons.bookOpen(),
  'book open text': PhosphorIcons.bookOpenText(),
  'book open user': PhosphorIcons.bookOpenUser(),
  'bookmark': PhosphorIcons.bookmark(),
  'bookmark simple': PhosphorIcons.bookmarkSimple(),
  'bookmarks': PhosphorIcons.bookmarks(),
  'bookmarks simple': PhosphorIcons.bookmarksSimple(),
  'books': PhosphorIcons.books(),
  'boot': PhosphorIcons.boot(),
  'boules': PhosphorIcons.boules(),
  'bounding box': PhosphorIcons.boundingBox(),
  'bowl food': PhosphorIcons.bowlFood(),
  'bowl steam': PhosphorIcons.bowlSteam(),
  'bowling ball': PhosphorIcons.bowlingBall(),
  'box arrow down': PhosphorIcons.boxArrowDown(),
  'box arrow up': PhosphorIcons.boxArrowUp(),
  'boxing glove': PhosphorIcons.boxingGlove(),
  'brackets angle': PhosphorIcons.bracketsAngle(),
  'brackets curly': PhosphorIcons.bracketsCurly(),
  'brackets round': PhosphorIcons.bracketsRound(),
  'brackets square': PhosphorIcons.bracketsSquare(),
  'brain': PhosphorIcons.brain(),
  'brandy': PhosphorIcons.brandy(),
  'bread': PhosphorIcons.bread(),
  'bridge': PhosphorIcons.bridge(),
  'briefcase': PhosphorIcons.briefcase(),
  'briefcase metal': PhosphorIcons.briefcaseMetal(),
  'broadcast': PhosphorIcons.broadcast(),
  'broom': PhosphorIcons.broom(),
  'browser': PhosphorIcons.browser(),
  'browsers': PhosphorIcons.browsers(),
  'bug': PhosphorIcons.bug(),
  'bug beetle': PhosphorIcons.bugBeetle(),
  'bug droid': PhosphorIcons.bugDroid(),
  'building': PhosphorIcons.building(),
  'building apartment': PhosphorIcons.buildingApartment(),
  'building office': PhosphorIcons.buildingOffice(),
  'buildings': PhosphorIcons.buildings(),
  'bulldozer': PhosphorIcons.bulldozer(),
  'bus': PhosphorIcons.bus(),
  'butterfly': PhosphorIcons.butterfly(),
  'cable car': PhosphorIcons.cableCar(),
  'cactus': PhosphorIcons.cactus(),
  'cake': PhosphorIcons.cake(),
  'calculator': PhosphorIcons.calculator(),
  'calendar': PhosphorIcons.calendar(),
  'calendar blank': PhosphorIcons.calendarBlank(),
  'calendar check': PhosphorIcons.calendarCheck(),
  'calendar dot': PhosphorIcons.calendarDot(),
  'calendar dots': PhosphorIcons.calendarDots(),
  'calendar heart': PhosphorIcons.calendarHeart(),
  'calendar minus': PhosphorIcons.calendarMinus(),
  'calendar plus': PhosphorIcons.calendarPlus(),
  'calendar slash': PhosphorIcons.calendarSlash(),
  'calendar star': PhosphorIcons.calendarStar(),
  'calendar x': PhosphorIcons.calendarX(),
  'call bell': PhosphorIcons.callBell(),
  'camera': PhosphorIcons.camera(),
  'camera plus': PhosphorIcons.cameraPlus(),
  'camera rotate': PhosphorIcons.cameraRotate(),
  'camera slash': PhosphorIcons.cameraSlash(),
  'campfire': PhosphorIcons.campfire(),
  'car': PhosphorIcons.car(),
  'car battery': PhosphorIcons.carBattery(),
  'car profile': PhosphorIcons.carProfile(),
  'car simple': PhosphorIcons.carSimple(),
  'cardholder': PhosphorIcons.cardholder(),
  'cards': PhosphorIcons.cards(),
  'cards three': PhosphorIcons.cardsThree(),
  'caret circle double down': PhosphorIcons.caretCircleDoubleDown(),
  'caret circle double left': PhosphorIcons.caretCircleDoubleLeft(),
  'caret circle double right': PhosphorIcons.caretCircleDoubleRight(),
  'caret circle double up': PhosphorIcons.caretCircleDoubleUp(),
  'caret circle down': PhosphorIcons.caretCircleDown(),
  'caret circle left': PhosphorIcons.caretCircleLeft(),
  'caret circle right': PhosphorIcons.caretCircleRight(),
  'caret circle up': PhosphorIcons.caretCircleUp(),
  'caret circle up down': PhosphorIcons.caretCircleUpDown(),
  'caret double down': PhosphorIcons.caretDoubleDown(),
  'caret double left': PhosphorIcons.caretDoubleLeft(),
  'caret double right': PhosphorIcons.caretDoubleRight(),
  'caret double up': PhosphorIcons.caretDoubleUp(),
  'caret down': PhosphorIcons.caretDown(),
  'caret left': PhosphorIcons.caretLeft(),
  'caret line down': PhosphorIcons.caretLineDown(),
  'caret line left': PhosphorIcons.caretLineLeft(),
  'caret line right': PhosphorIcons.caretLineRight(),
  'caret line up': PhosphorIcons.caretLineUp(),
  'caret right': PhosphorIcons.caretRight(),
  'caret up': PhosphorIcons.caretUp(),
  'caret up down': PhosphorIcons.caretUpDown(),
  'carrot': PhosphorIcons.carrot(),
  'cash register': PhosphorIcons.cashRegister(),
  'cassette tape': PhosphorIcons.cassetteTape(),
  'castle turret': PhosphorIcons.castleTurret(),
  'cat': PhosphorIcons.cat(),
  'cell signal full': PhosphorIcons.cellSignalFull(),
  'cell signal high': PhosphorIcons.cellSignalHigh(),
  'cell signal low': PhosphorIcons.cellSignalLow(),
  'cell signal medium': PhosphorIcons.cellSignalMedium(),
  'cell signal none': PhosphorIcons.cellSignalNone(),
  'cell signal slash': PhosphorIcons.cellSignalSlash(),
  'cell signal x': PhosphorIcons.cellSignalX(),
  'cell tower': PhosphorIcons.cellTower(),
  'certificate': PhosphorIcons.certificate(),
  'chair': PhosphorIcons.chair(),
  'chalkboard': PhosphorIcons.chalkboard(),
  'chalkboard simple': PhosphorIcons.chalkboardSimple(),
  'chalkboard teacher': PhosphorIcons.chalkboardTeacher(),
  'champagne': PhosphorIcons.champagne(),
  'charging station': PhosphorIcons.chargingStation(),
  'chart bar': PhosphorIcons.chartBar(),
  'chart bar horizontal': PhosphorIcons.chartBarHorizontal(),
  'chart donut': PhosphorIcons.chartDonut(),
  'chart line': PhosphorIcons.chartLine(),
  'chart line down': PhosphorIcons.chartLineDown(),
  'chart line up': PhosphorIcons.chartLineUp(),
  'chart pie': PhosphorIcons.chartPie(),
  'chart pie slice': PhosphorIcons.chartPieSlice(),
  'chart polar': PhosphorIcons.chartPolar(),
  'chart scatter': PhosphorIcons.chartScatter(),
  'chat': PhosphorIcons.chat(),
  'chat centered': PhosphorIcons.chatCentered(),
  'chat centered dots': PhosphorIcons.chatCenteredDots(),
  'chat centered slash': PhosphorIcons.chatCenteredSlash(),
  'chat centered text': PhosphorIcons.chatCenteredText(),
  'chat circle': PhosphorIcons.chatCircle(),
  'chat circle dots': PhosphorIcons.chatCircleDots(),
  'chat circle slash': PhosphorIcons.chatCircleSlash(),
  'chat circle text': PhosphorIcons.chatCircleText(),
  'chat dots': PhosphorIcons.chatDots(),
  'chat slash': PhosphorIcons.chatSlash(),
  'chat teardrop': PhosphorIcons.chatTeardrop(),
  'chat teardrop dots': PhosphorIcons.chatTeardropDots(),
  'chat teardrop slash': PhosphorIcons.chatTeardropSlash(),
  'chat teardrop text': PhosphorIcons.chatTeardropText(),
  'chat text': PhosphorIcons.chatText(),
  'chats': PhosphorIcons.chats(),
  'chats circle': PhosphorIcons.chatsCircle(),
  'chats teardrop': PhosphorIcons.chatsTeardrop(),
  'check': PhosphorIcons.check(),
  'check circle': PhosphorIcons.checkCircle(),
  'check fat': PhosphorIcons.checkFat(),
  'check square': PhosphorIcons.checkSquare(),
  'check square offset': PhosphorIcons.checkSquareOffset(),
  'checkerboard': PhosphorIcons.checkerboard(),
  'checks': PhosphorIcons.checks(),
  'cheers': PhosphorIcons.cheers(),
  'cheese': PhosphorIcons.cheese(),
  'chef hat': PhosphorIcons.chefHat(),
  'cherries': PhosphorIcons.cherries(),
  'church': PhosphorIcons.church(),
  'cigarette': PhosphorIcons.cigarette(),
  'cigarette slash': PhosphorIcons.cigaretteSlash(),
  'circle': PhosphorIcons.circle(),
  'circle dashed': PhosphorIcons.circleDashed(),
  'circle half': PhosphorIcons.circleHalf(),
  'circle half tilt': PhosphorIcons.circleHalfTilt(),
  'circle notch': PhosphorIcons.circleNotch(),
  'circles four': PhosphorIcons.circlesFour(),
  'circles three': PhosphorIcons.circlesThree(),
  'circles three plus': PhosphorIcons.circlesThreePlus(),
  'circuitry': PhosphorIcons.circuitry(),
  'city': PhosphorIcons.city(),
  'clipboard': PhosphorIcons.clipboard(),
  'clipboard text': PhosphorIcons.clipboardText(),
  'clock': PhosphorIcons.clock(),
  'clock afternoon': PhosphorIcons.clockAfternoon(),
  'clock clockwise': PhosphorIcons.clockClockwise(),
  'clock countdown': PhosphorIcons.clockCountdown(),
  'clock counter clockwise': PhosphorIcons.clockCounterClockwise(),
  'clock user': PhosphorIcons.clockUser(),
  'closed captioning': PhosphorIcons.closedCaptioning(),
  'cloud': PhosphorIcons.cloud(),
  'cloud arrow down': PhosphorIcons.cloudArrowDown(),
  'cloud arrow up': PhosphorIcons.cloudArrowUp(),
  'cloud check': PhosphorIcons.cloudCheck(),
  'cloud fog': PhosphorIcons.cloudFog(),
  'cloud lightning': PhosphorIcons.cloudLightning(),
  'cloud moon': PhosphorIcons.cloudMoon(),
  'cloud rain': PhosphorIcons.cloudRain(),
  'cloud slash': PhosphorIcons.cloudSlash(),
  'cloud snow': PhosphorIcons.cloudSnow(),
  'cloud sun': PhosphorIcons.cloudSun(),
  'cloud warning': PhosphorIcons.cloudWarning(),
  'cloud x': PhosphorIcons.cloudX(),
  'clover': PhosphorIcons.clover(),
  'club': PhosphorIcons.club(),
  'coat hanger': PhosphorIcons.coatHanger(),
  'coda logo': PhosphorIcons.codaLogo(),
  'code': PhosphorIcons.code(),
  'code block': PhosphorIcons.codeBlock(),
  'code simple': PhosphorIcons.codeSimple(),
  'codepen logo': PhosphorIcons.codepenLogo(),
  'codesandbox logo': PhosphorIcons.codesandboxLogo(),
  'coffee': PhosphorIcons.coffee(),
  'coffee bean': PhosphorIcons.coffeeBean(),
  'coin': PhosphorIcons.coin(),
  'coin vertical': PhosphorIcons.coinVertical(),
  'coins': PhosphorIcons.coins(),
  'columns': PhosphorIcons.columns(),
  'columns plus left': PhosphorIcons.columnsPlusLeft(),
  'columns plus right': PhosphorIcons.columnsPlusRight(),
  'command': PhosphorIcons.command(),
  'compass': PhosphorIcons.compass(),
  'compass rose': PhosphorIcons.compassRose(),
  'compass tool': PhosphorIcons.compassTool(),
  'computer tower': PhosphorIcons.computerTower(),
  'confetti': PhosphorIcons.confetti(),
  'contactless payment': PhosphorIcons.contactlessPayment(),
  'control': PhosphorIcons.control(),
  'cookie': PhosphorIcons.cookie(),
  'cooking pot': PhosphorIcons.cookingPot(),
  'copy': PhosphorIcons.copy(),
  'copy simple': PhosphorIcons.copySimple(),
  'copyleft': PhosphorIcons.copyleft(),
  'copyright': PhosphorIcons.copyright(),
  'corners in': PhosphorIcons.cornersIn(),
  'corners out': PhosphorIcons.cornersOut(),
  'couch': PhosphorIcons.couch(),
  'court basketball': PhosphorIcons.courtBasketball(),
  'cow': PhosphorIcons.cow(),
  'cowboy hat': PhosphorIcons.cowboyHat(),
  'cpu': PhosphorIcons.cpu(),
  'crane': PhosphorIcons.crane(),
  'crane tower': PhosphorIcons.craneTower(),
  'credit card': PhosphorIcons.creditCard(),
  'cricket': PhosphorIcons.cricket(),
  'crop': PhosphorIcons.crop(),
  'cross': PhosphorIcons.cross(),
  'crosshair': PhosphorIcons.crosshair(),
  'crosshair simple': PhosphorIcons.crosshairSimple(),
  'crown': PhosphorIcons.crown(),
  'crown cross': PhosphorIcons.crownCross(),
  'crown simple': PhosphorIcons.crownSimple(),
  'cube': PhosphorIcons.cube(),
  'cube focus': PhosphorIcons.cubeFocus(),
  'cube transparent': PhosphorIcons.cubeTransparent(),
  'currency btc': PhosphorIcons.currencyBtc(),
  'currency circle dollar': PhosphorIcons.currencyCircleDollar(),
  'currency cny': PhosphorIcons.currencyCny(),
  'currency dollar': PhosphorIcons.currencyDollar(),
  'currency dollar simple': PhosphorIcons.currencyDollarSimple(),
  'currency eth': PhosphorIcons.currencyEth(),
  'currency eur': PhosphorIcons.currencyEur(),
  'currency gbp': PhosphorIcons.currencyGbp(),
  'currency inr': PhosphorIcons.currencyInr(),
  'currency jpy': PhosphorIcons.currencyJpy(),
  'currency krw': PhosphorIcons.currencyKrw(),
  'currency kzt': PhosphorIcons.currencyKzt(),
  'currency ngn': PhosphorIcons.currencyNgn(),
  'currency rub': PhosphorIcons.currencyRub(),
  'cursor': PhosphorIcons.cursor(),
  'cursor click': PhosphorIcons.cursorClick(),
  'cursor text': PhosphorIcons.cursorText(),
  'cylinder': PhosphorIcons.cylinder(),
  'database': PhosphorIcons.database(),
  'desk': PhosphorIcons.desk(),
  'desktop': PhosphorIcons.desktop(),
  'desktop tower': PhosphorIcons.desktopTower(),
  'detective': PhosphorIcons.detective(),
  'dev to logo': PhosphorIcons.devToLogo(),
  'device mobile': PhosphorIcons.deviceMobile(),
  'device mobile camera': PhosphorIcons.deviceMobileCamera(),
  'device mobile slash': PhosphorIcons.deviceMobileSlash(),
  'device mobile speaker': PhosphorIcons.deviceMobileSpeaker(),
  'device rotate': PhosphorIcons.deviceRotate(),
  'device tablet': PhosphorIcons.deviceTablet(),
  'device tablet camera': PhosphorIcons.deviceTabletCamera(),
  'device tablet speaker': PhosphorIcons.deviceTabletSpeaker(),
  'devices': PhosphorIcons.devices(),
  'diamond': PhosphorIcons.diamond(),
  'diamonds four': PhosphorIcons.diamondsFour(),
  'dice five': PhosphorIcons.diceFive(),
  'dice four': PhosphorIcons.diceFour(),
  'dice one': PhosphorIcons.diceOne(),
  'dice six': PhosphorIcons.diceSix(),
  'dice three': PhosphorIcons.diceThree(),
  'dice two': PhosphorIcons.diceTwo(),
  'disc': PhosphorIcons.disc(),
  'disco ball': PhosphorIcons.discoBall(),
  'discord logo': PhosphorIcons.discordLogo(),
  'divide': PhosphorIcons.divide(),
  'dna': PhosphorIcons.dna(),
  'dog': PhosphorIcons.dog(),
  'door': PhosphorIcons.door(),
  'door open': PhosphorIcons.doorOpen(),
  'dot': PhosphorIcons.dot(),
  'dot outline': PhosphorIcons.dotOutline(),
  'dots nine': PhosphorIcons.dotsNine(),
  'dots six': PhosphorIcons.dotsSix(),
  'dots six vertical': PhosphorIcons.dotsSixVertical(),
  'dots three': PhosphorIcons.dotsThree(),
  'dots three circle': PhosphorIcons.dotsThreeCircle(),
  'dots three circle vertical': PhosphorIcons.dotsThreeCircleVertical(),
  'dots three outline': PhosphorIcons.dotsThreeOutline(),
  'dots three outline vertical': PhosphorIcons.dotsThreeOutlineVertical(),
  'dots three vertical': PhosphorIcons.dotsThreeVertical(),
  'download': PhosphorIcons.download(),
  'download simple': PhosphorIcons.downloadSimple(),
  'dress': PhosphorIcons.dress(),
  'dresser': PhosphorIcons.dresser(),
  'dribbble logo': PhosphorIcons.dribbbleLogo(),
  'drone': PhosphorIcons.drone(),
  'drop': PhosphorIcons.drop(),
  'drop half': PhosphorIcons.dropHalf(),
  'drop half bottom': PhosphorIcons.dropHalfBottom(),
  'drop simple': PhosphorIcons.dropSimple(),
  'drop slash': PhosphorIcons.dropSlash(),
  'dropbox logo': PhosphorIcons.dropboxLogo(),
  'ear': PhosphorIcons.ear(),
  'ear slash': PhosphorIcons.earSlash(),
  'egg': PhosphorIcons.egg(),
  'egg crack': PhosphorIcons.eggCrack(),
  'eject': PhosphorIcons.eject(),
  'eject simple': PhosphorIcons.ejectSimple(),
  'elevator': PhosphorIcons.elevator(),
  'empty': PhosphorIcons.empty(),
  'engine': PhosphorIcons.engine(),
  'envelope': PhosphorIcons.envelope(),
  'envelope open': PhosphorIcons.envelopeOpen(),
  'envelope simple': PhosphorIcons.envelopeSimple(),
  'envelope simple open': PhosphorIcons.envelopeSimpleOpen(),
  'equalizer': PhosphorIcons.equalizer(),
  'equals': PhosphorIcons.equals(),
  'eraser': PhosphorIcons.eraser(),
  'escalator down': PhosphorIcons.escalatorDown(),
  'escalator up': PhosphorIcons.escalatorUp(),
  'exam': PhosphorIcons.exam(),
  'exclamation mark': PhosphorIcons.exclamationMark(),
  'exclude': PhosphorIcons.exclude(),
  'exclude square': PhosphorIcons.excludeSquare(),
  'export': PhosphorIcons.export(),
  'eye': PhosphorIcons.eye(),
  'eye closed': PhosphorIcons.eyeClosed(),
  'eye slash': PhosphorIcons.eyeSlash(),
  'eyedropper': PhosphorIcons.eyedropper(),
  'eyedropper sample': PhosphorIcons.eyedropperSample(),
  'eyeglasses': PhosphorIcons.eyeglasses(),
  'eyes': PhosphorIcons.eyes(),
  'face mask': PhosphorIcons.faceMask(),
  'facebook logo': PhosphorIcons.facebookLogo(),
  'factory': PhosphorIcons.factory(),
  'faders': PhosphorIcons.faders(),
  'faders horizontal': PhosphorIcons.fadersHorizontal(),
  'fallout shelter': PhosphorIcons.falloutShelter(),
  'fan': PhosphorIcons.fan(),
  'farm': PhosphorIcons.farm(),
  'fast forward': PhosphorIcons.fastForward(),
  'fast forward circle': PhosphorIcons.fastForwardCircle(),
  'feather': PhosphorIcons.feather(),
  'fediverse logo': PhosphorIcons.fediverseLogo(),
  'figma logo': PhosphorIcons.figmaLogo(),
  'file': PhosphorIcons.file(),
  'file archive': PhosphorIcons.fileArchive(),
  'file arrow down': PhosphorIcons.fileArrowDown(),
  'file arrow up': PhosphorIcons.fileArrowUp(),
  'file audio': PhosphorIcons.fileAudio(),
  'file c': PhosphorIcons.fileC(),
  'file c sharp': PhosphorIcons.fileCSharp(),
  'file cloud': PhosphorIcons.fileCloud(),
  'file code': PhosphorIcons.fileCode(),
  'file cpp': PhosphorIcons.fileCpp(),
  'file css': PhosphorIcons.fileCss(),
  'file csv': PhosphorIcons.fileCsv(),
  'file dashed': PhosphorIcons.fileDashed(),
  'file doc': PhosphorIcons.fileDoc(),
  'file html': PhosphorIcons.fileHtml(),
  'file image': PhosphorIcons.fileImage(),
  'file ini': PhosphorIcons.fileIni(),
  'file jpg': PhosphorIcons.fileJpg(),
  'file js': PhosphorIcons.fileJs(),
  'file jsx': PhosphorIcons.fileJsx(),
  'file lock': PhosphorIcons.fileLock(),
  'file magnifying glass': PhosphorIcons.fileMagnifyingGlass(),
  'file md': PhosphorIcons.fileMd(),
  'file minus': PhosphorIcons.fileMinus(),
  'file pdf': PhosphorIcons.filePdf(),
  'file plus': PhosphorIcons.filePlus(),
  'file png': PhosphorIcons.filePng(),
  'file ppt': PhosphorIcons.filePpt(),
  'file py': PhosphorIcons.filePy(),
  'file rs': PhosphorIcons.fileRs(),
  'file sql': PhosphorIcons.fileSql(),
  'file svg': PhosphorIcons.fileSvg(),
  'file text': PhosphorIcons.fileText(),
  'file ts': PhosphorIcons.fileTs(),
  'file tsx': PhosphorIcons.fileTsx(),
  'file txt': PhosphorIcons.fileTxt(),
  'file video': PhosphorIcons.fileVideo(),
  'file vue': PhosphorIcons.fileVue(),
  'file x': PhosphorIcons.fileX(),
  'file xls': PhosphorIcons.fileXls(),
  'file zip': PhosphorIcons.fileZip(),
  'files': PhosphorIcons.files(),
  'film reel': PhosphorIcons.filmReel(),
  'film script': PhosphorIcons.filmScript(),
  'film slate': PhosphorIcons.filmSlate(),
  'film strip': PhosphorIcons.filmStrip(),
  'fingerprint': PhosphorIcons.fingerprint(),
  'fingerprint simple': PhosphorIcons.fingerprintSimple(),
  'finn the human': PhosphorIcons.finnTheHuman(),
  'fire': PhosphorIcons.fire(),
  'fire extinguisher': PhosphorIcons.fireExtinguisher(),
  'fire simple': PhosphorIcons.fireSimple(),
  'fire truck': PhosphorIcons.fireTruck(),
  'first aid': PhosphorIcons.firstAid(),
  'first aid kit': PhosphorIcons.firstAidKit(),
  'fish': PhosphorIcons.fish(),
  'fish simple': PhosphorIcons.fishSimple(),
  'flag': PhosphorIcons.flag(),
  'flag banner': PhosphorIcons.flagBanner(),
  'flag banner fold': PhosphorIcons.flagBannerFold(),
  'flag checkered': PhosphorIcons.flagCheckered(),
  'flag pennant': PhosphorIcons.flagPennant(),
  'flame': PhosphorIcons.flame(),
  'flashlight': PhosphorIcons.flashlight(),
  'flask': PhosphorIcons.flask(),
  'flip horizontal': PhosphorIcons.flipHorizontal(),
  'flip vertical': PhosphorIcons.flipVertical(),
  'floppy disk': PhosphorIcons.floppyDisk(),
  'floppy disk back': PhosphorIcons.floppyDiskBack(),
  'flow arrow': PhosphorIcons.flowArrow(),
  'flower': PhosphorIcons.flower(),
  'flower lotus': PhosphorIcons.flowerLotus(),
  'flower tulip': PhosphorIcons.flowerTulip(),
  'flying saucer': PhosphorIcons.flyingSaucer(),
  'folder': PhosphorIcons.folder(),
  'folder dashed': PhosphorIcons.folderDashed(),
  'folder lock': PhosphorIcons.folderLock(),
  'folder minus': PhosphorIcons.folderMinus(),
  'folder open': PhosphorIcons.folderOpen(),
  'folder plus': PhosphorIcons.folderPlus(),
  'folder simple': PhosphorIcons.folderSimple(),
  'folder simple dashed': PhosphorIcons.folderSimpleDashed(),
  'folder simple lock': PhosphorIcons.folderSimpleLock(),
  'folder simple minus': PhosphorIcons.folderSimpleMinus(),
  'folder simple plus': PhosphorIcons.folderSimplePlus(),
  'folder simple star': PhosphorIcons.folderSimpleStar(),
  'folder simple user': PhosphorIcons.folderSimpleUser(),
  'folder star': PhosphorIcons.folderStar(),
  'folder user': PhosphorIcons.folderUser(),
  'folders': PhosphorIcons.folders(),
  'football': PhosphorIcons.football(),
  'football helmet': PhosphorIcons.footballHelmet(),
  'footprints': PhosphorIcons.footprints(),
  'fork knife': PhosphorIcons.forkKnife(),
  'four k': PhosphorIcons.fourK(),
  'frame corners': PhosphorIcons.frameCorners(),
  'framer logo': PhosphorIcons.framerLogo(),
  'function': PhosphorIcons.function(),
  'funnel': PhosphorIcons.funnel(),
  'funnel simple': PhosphorIcons.funnelSimple(),
  'funnel simple x': PhosphorIcons.funnelSimpleX(),
  'funnel x': PhosphorIcons.funnelX(),
  'game controller': PhosphorIcons.gameController(),
  'garage': PhosphorIcons.garage(),
  'gas can': PhosphorIcons.gasCan(),
  'gas pump': PhosphorIcons.gasPump(),
  'gauge': PhosphorIcons.gauge(),
  'gavel': PhosphorIcons.gavel(),
  'gear': PhosphorIcons.gear(),
  'gear fine': PhosphorIcons.gearFine(),
  'gear six': PhosphorIcons.gearSix(),
  'gender female': PhosphorIcons.genderFemale(),
  'gender intersex': PhosphorIcons.genderIntersex(),
  'gender male': PhosphorIcons.genderMale(),
  'gender neuter': PhosphorIcons.genderNeuter(),
  'gender nonbinary': PhosphorIcons.genderNonbinary(),
  'gender transgender': PhosphorIcons.genderTransgender(),
  'ghost': PhosphorIcons.ghost(),
  'gif': PhosphorIcons.gif(),
  'gift': PhosphorIcons.gift(),
  'git branch': PhosphorIcons.gitBranch(),
  'git commit': PhosphorIcons.gitCommit(),
  'git diff': PhosphorIcons.gitDiff(),
  'git fork': PhosphorIcons.gitFork(),
  'git merge': PhosphorIcons.gitMerge(),
  'git pull request': PhosphorIcons.gitPullRequest(),
  'github logo': PhosphorIcons.githubLogo(),
  'gitlab logo': PhosphorIcons.gitlabLogo(),
  'gitlab logo simple': PhosphorIcons.gitlabLogoSimple(),
  'globe': PhosphorIcons.globe(),
  'globe hemisphere east': PhosphorIcons.globeHemisphereEast(),
  'globe hemisphere west': PhosphorIcons.globeHemisphereWest(),
  'globe simple': PhosphorIcons.globeSimple(),
  'globe simple x': PhosphorIcons.globeSimpleX(),
  'globe stand': PhosphorIcons.globeStand(),
  'globe x': PhosphorIcons.globeX(),
  'goggles': PhosphorIcons.goggles(),
  'golf': PhosphorIcons.golf(),
  'goodreads logo': PhosphorIcons.goodreadsLogo(),
  'google cardboard logo': PhosphorIcons.googleCardboardLogo(),
  'google chrome logo': PhosphorIcons.googleChromeLogo(),
  'google drive logo': PhosphorIcons.googleDriveLogo(),
  'google logo': PhosphorIcons.googleLogo(),
  'google photos logo': PhosphorIcons.googlePhotosLogo(),
  'google play logo': PhosphorIcons.googlePlayLogo(),
  'google podcasts logo': PhosphorIcons.googlePodcastsLogo(),
  'gps': PhosphorIcons.gps(),
  'gps fix': PhosphorIcons.gpsFix(),
  'gps slash': PhosphorIcons.gpsSlash(),
  'gradient': PhosphorIcons.gradient(),
  'graduation cap': PhosphorIcons.graduationCap(),
  'grains': PhosphorIcons.grains(),
  'grains slash': PhosphorIcons.grainsSlash(),
  'graph': PhosphorIcons.graph(),
  'graphics card': PhosphorIcons.graphicsCard(),
  'greater than': PhosphorIcons.greaterThan(),
  'greater than or equal': PhosphorIcons.greaterThanOrEqual(),
  'grid four': PhosphorIcons.gridFour(),
  'grid nine': PhosphorIcons.gridNine(),
  'guitar': PhosphorIcons.guitar(),
  'hair dryer': PhosphorIcons.hairDryer(),
  'hamburger': PhosphorIcons.hamburger(),
  'hammer': PhosphorIcons.hammer(),
  'hand': PhosphorIcons.hand(),
  'hand arrow down': PhosphorIcons.handArrowDown(),
  'hand arrow up': PhosphorIcons.handArrowUp(),
  'hand coins': PhosphorIcons.handCoins(),
  'hand deposit': PhosphorIcons.handDeposit(),
  'hand eye': PhosphorIcons.handEye(),
  'hand fist': PhosphorIcons.handFist(),
  'hand grabbing': PhosphorIcons.handGrabbing(),
  'hand heart': PhosphorIcons.handHeart(),
  'hand palm': PhosphorIcons.handPalm(),
  'hand peace': PhosphorIcons.handPeace(),
  'hand pointing': PhosphorIcons.handPointing(),
  'hand soap': PhosphorIcons.handSoap(),
  'hand swipe left': PhosphorIcons.handSwipeLeft(),
  'hand swipe right': PhosphorIcons.handSwipeRight(),
  'hand tap': PhosphorIcons.handTap(),
  'hand waving': PhosphorIcons.handWaving(),
  'hand withdraw': PhosphorIcons.handWithdraw(),
  'handbag': PhosphorIcons.handbag(),
  'handbag simple': PhosphorIcons.handbagSimple(),
  'hands clapping': PhosphorIcons.handsClapping(),
  'hands praying': PhosphorIcons.handsPraying(),
  'handshake': PhosphorIcons.handshake(),
  'hard drive': PhosphorIcons.hardDrive(),
  'hard drives': PhosphorIcons.hardDrives(),
  'hard hat': PhosphorIcons.hardHat(),
  'hash': PhosphorIcons.hash(),
  'hash straight': PhosphorIcons.hashStraight(),
  'head circuit': PhosphorIcons.headCircuit(),
  'headlights': PhosphorIcons.headlights(),
  'headphones': PhosphorIcons.headphones(),
  'headset': PhosphorIcons.headset(),
  'heart': PhosphorIcons.heart(),
  'heart break': PhosphorIcons.heartBreak(),
  'heart half': PhosphorIcons.heartHalf(),
  'heart straight': PhosphorIcons.heartStraight(),
  'heart straight break': PhosphorIcons.heartStraightBreak(),
  'heartbeat': PhosphorIcons.heartbeat(),
  'hexagon': PhosphorIcons.hexagon(),
  'high definition': PhosphorIcons.highDefinition(),
  'high heel': PhosphorIcons.highHeel(),
  'highlighter': PhosphorIcons.highlighter(),
  'highlighter circle': PhosphorIcons.highlighterCircle(),
  'hockey': PhosphorIcons.hockey(),
  'hoodie': PhosphorIcons.hoodie(),
  'horse': PhosphorIcons.horse(),
  'hospital': PhosphorIcons.hospital(),
  'hourglass': PhosphorIcons.hourglass(),
  'hourglass high': PhosphorIcons.hourglassHigh(),
  'hourglass low': PhosphorIcons.hourglassLow(),
  'hourglass medium': PhosphorIcons.hourglassMedium(),
  'hourglass simple': PhosphorIcons.hourglassSimple(),
  'hourglass simple high': PhosphorIcons.hourglassSimpleHigh(),
  'hourglass simple low': PhosphorIcons.hourglassSimpleLow(),
  'hourglass simple medium': PhosphorIcons.hourglassSimpleMedium(),
  'house': PhosphorIcons.house(),
  'house line': PhosphorIcons.houseLine(),
  'house simple': PhosphorIcons.houseSimple(),
  'hurricane': PhosphorIcons.hurricane(),
  'ice cream': PhosphorIcons.iceCream(),
  'identification badge': PhosphorIcons.identificationBadge(),
  'identification card': PhosphorIcons.identificationCard(),
  'image': PhosphorIcons.image(),
  'image broken': PhosphorIcons.imageBroken(),
  'image square': PhosphorIcons.imageSquare(),
  'images': PhosphorIcons.images(),
  'images square': PhosphorIcons.imagesSquare(),
  'infinity': PhosphorIcons.infinity(),
  'info': PhosphorIcons.info(),
  'instagram logo': PhosphorIcons.instagramLogo(),
  'intersect': PhosphorIcons.intersect(),
  'intersect square': PhosphorIcons.intersectSquare(),
  'intersect three': PhosphorIcons.intersectThree(),
  'intersection': PhosphorIcons.intersection(),
  'invoice': PhosphorIcons.invoice(),
  'island': PhosphorIcons.island(),
  'jar': PhosphorIcons.jar(),
  'jar label': PhosphorIcons.jarLabel(),
  'jeep': PhosphorIcons.jeep(),
  'joystick': PhosphorIcons.joystick(),
  'kanban': PhosphorIcons.kanban(),
  'key': PhosphorIcons.key(),
  'key return': PhosphorIcons.keyReturn(),
  'keyboard': PhosphorIcons.keyboard(),
  'keyhole': PhosphorIcons.keyhole(),
  'knife': PhosphorIcons.knife(),
  'ladder': PhosphorIcons.ladder(),
  'ladder simple': PhosphorIcons.ladderSimple(),
  'lamp': PhosphorIcons.lamp(),
  'lamp pendant': PhosphorIcons.lampPendant(),
  'laptop': PhosphorIcons.laptop(),
  'lasso': PhosphorIcons.lasso(),
  'lastfm logo': PhosphorIcons.lastfmLogo(),
  'layout': PhosphorIcons.layout(),
  'leaf': PhosphorIcons.leaf(),
  'lectern': PhosphorIcons.lectern(),
  'lego': PhosphorIcons.lego(),
  'lego smiley': PhosphorIcons.legoSmiley(),
  'less than': PhosphorIcons.lessThan(),
  'less than or equal': PhosphorIcons.lessThanOrEqual(),
  'letter circle h': PhosphorIcons.letterCircleH(),
  'letter circle p': PhosphorIcons.letterCircleP(),
  'letter circle v': PhosphorIcons.letterCircleV(),
  'lifebuoy': PhosphorIcons.lifebuoy(),
  'lightbulb': PhosphorIcons.lightbulb(),
  'lightbulb filament': PhosphorIcons.lightbulbFilament(),
  'lighthouse': PhosphorIcons.lighthouse(),
  'lightning': PhosphorIcons.lightning(),
  'lightning a': PhosphorIcons.lightningA(),
  'lightning slash': PhosphorIcons.lightningSlash(),
  'line segment': PhosphorIcons.lineSegment(),
  'line segments': PhosphorIcons.lineSegments(),
  'line vertical': PhosphorIcons.lineVertical(),
  'link': PhosphorIcons.link(),
  'link break': PhosphorIcons.linkBreak(),
  'link simple': PhosphorIcons.linkSimple(),
  'link simple break': PhosphorIcons.linkSimpleBreak(),
  'link simple horizontal': PhosphorIcons.linkSimpleHorizontal(),
  'link simple horizontal break': PhosphorIcons.linkSimpleHorizontalBreak(),
  'linkedin logo': PhosphorIcons.linkedinLogo(),
  'linktree logo': PhosphorIcons.linktreeLogo(),
  'linux logo': PhosphorIcons.linuxLogo(),
  'list': PhosphorIcons.list(),
  'list bullets': PhosphorIcons.listBullets(),
  'list checks': PhosphorIcons.listChecks(),
  'list dashes': PhosphorIcons.listDashes(),
  'list heart': PhosphorIcons.listHeart(),
  'list magnifying glass': PhosphorIcons.listMagnifyingGlass(),
  'list numbers': PhosphorIcons.listNumbers(),
  'list plus': PhosphorIcons.listPlus(),
  'list star': PhosphorIcons.listStar(),
  'lock': PhosphorIcons.lock(),
  'lock key': PhosphorIcons.lockKey(),
  'lock key open': PhosphorIcons.lockKeyOpen(),
  'lock laminated': PhosphorIcons.lockLaminated(),
  'lock laminated open': PhosphorIcons.lockLaminatedOpen(),
  'lock open': PhosphorIcons.lockOpen(),
  'lock simple': PhosphorIcons.lockSimple(),
  'lock simple open': PhosphorIcons.lockSimpleOpen(),
  'lockers': PhosphorIcons.lockers(),
  'log': PhosphorIcons.log(),
  'magic wand': PhosphorIcons.magicWand(),
  'magnet': PhosphorIcons.magnet(),
  'magnet straight': PhosphorIcons.magnetStraight(),
  'magnifying glass': PhosphorIcons.magnifyingGlass(),
  'magnifying glass minus': PhosphorIcons.magnifyingGlassMinus(),
  'magnifying glass plus': PhosphorIcons.magnifyingGlassPlus(),
  'mailbox': PhosphorIcons.mailbox(),
  'map pin': PhosphorIcons.mapPin(),
  'map pin area': PhosphorIcons.mapPinArea(),
  'map pin line': PhosphorIcons.mapPinLine(),
  'map pin plus': PhosphorIcons.mapPinPlus(),
  'map pin simple': PhosphorIcons.mapPinSimple(),
  'map pin simple area': PhosphorIcons.mapPinSimpleArea(),
  'map pin simple line': PhosphorIcons.mapPinSimpleLine(),
  'map trifold': PhosphorIcons.mapTrifold(),
  'markdown logo': PhosphorIcons.markdownLogo(),
  'marker circle': PhosphorIcons.markerCircle(),
  'martini': PhosphorIcons.martini(),
  'mask happy': PhosphorIcons.maskHappy(),
  'mask sad': PhosphorIcons.maskSad(),
  'mastodon logo': PhosphorIcons.mastodonLogo(),
  'math operations': PhosphorIcons.mathOperations(),
  'matrix logo': PhosphorIcons.matrixLogo(),
  'medal': PhosphorIcons.medal(),
  'medal military': PhosphorIcons.medalMilitary(),
  'medium logo': PhosphorIcons.mediumLogo(),
  'megaphone': PhosphorIcons.megaphone(),
  'megaphone simple': PhosphorIcons.megaphoneSimple(),
  'member of': PhosphorIcons.memberOf(),
  'memory': PhosphorIcons.memory(),
  'messenger logo': PhosphorIcons.messengerLogo(),
  'meta logo': PhosphorIcons.metaLogo(),
  'meteor': PhosphorIcons.meteor(),
  'metronome': PhosphorIcons.metronome(),
  'microphone': PhosphorIcons.microphone(),
  'microphone slash': PhosphorIcons.microphoneSlash(),
  'microphone stage': PhosphorIcons.microphoneStage(),
  'microscope': PhosphorIcons.microscope(),
  'microsoft excel logo': PhosphorIcons.microsoftExcelLogo(),
  'microsoft outlook logo': PhosphorIcons.microsoftOutlookLogo(),
  'microsoft powerpoint logo': PhosphorIcons.microsoftPowerpointLogo(),
  'microsoft teams logo': PhosphorIcons.microsoftTeamsLogo(),
  'microsoft word logo': PhosphorIcons.microsoftWordLogo(),
  'minus': PhosphorIcons.minus(),
  'minus circle': PhosphorIcons.minusCircle(),
  'minus square': PhosphorIcons.minusSquare(),
  'money': PhosphorIcons.money(),
  'money wavy': PhosphorIcons.moneyWavy(),
  'monitor': PhosphorIcons.monitor(),
  'monitor arrow up': PhosphorIcons.monitorArrowUp(),
  'monitor play': PhosphorIcons.monitorPlay(),
  'moon': PhosphorIcons.moon(),
  'moon stars': PhosphorIcons.moonStars(),
  'moped': PhosphorIcons.moped(),
  'moped front': PhosphorIcons.mopedFront(),
  'mosque': PhosphorIcons.mosque(),
  'motorcycle': PhosphorIcons.motorcycle(),
  'mountains': PhosphorIcons.mountains(),
  'mouse': PhosphorIcons.mouse(),
  'mouse left click': PhosphorIcons.mouseLeftClick(),
  'mouse middle click': PhosphorIcons.mouseMiddleClick(),
  'mouse right click': PhosphorIcons.mouseRightClick(),
  'mouse scroll': PhosphorIcons.mouseScroll(),
  'mouse simple': PhosphorIcons.mouseSimple(),
  'music note': PhosphorIcons.musicNote(),
  'music note simple': PhosphorIcons.musicNoteSimple(),
  'music notes': PhosphorIcons.musicNotes(),
  'music notes minus': PhosphorIcons.musicNotesMinus(),
  'music notes plus': PhosphorIcons.musicNotesPlus(),
  'music notes simple': PhosphorIcons.musicNotesSimple(),
  'navigation arrow': PhosphorIcons.navigationArrow(),
  'needle': PhosphorIcons.needle(),
  'network': PhosphorIcons.network(),
  'network slash': PhosphorIcons.networkSlash(),
  'network x': PhosphorIcons.networkX(),
  'newspaper': PhosphorIcons.newspaper(),
  'newspaper clipping': PhosphorIcons.newspaperClipping(),
  'not equals': PhosphorIcons.notEquals(),
  'not member of': PhosphorIcons.notMemberOf(),
  'not subset of': PhosphorIcons.notSubsetOf(),
  'not superset of': PhosphorIcons.notSupersetOf(),
  'notches': PhosphorIcons.notches(),
  'note': PhosphorIcons.note(),
  'note blank': PhosphorIcons.noteBlank(),
  'note pencil': PhosphorIcons.notePencil(),
  'notebook': PhosphorIcons.notebook(),
  'notepad': PhosphorIcons.notepad(),
  'notification': PhosphorIcons.notification(),
  'notion logo': PhosphorIcons.notionLogo(),
  'nuclear plant': PhosphorIcons.nuclearPlant(),
  'number circle eight': PhosphorIcons.numberCircleEight(),
  'number circle five': PhosphorIcons.numberCircleFive(),
  'number circle four': PhosphorIcons.numberCircleFour(),
  'number circle nine': PhosphorIcons.numberCircleNine(),
  'number circle one': PhosphorIcons.numberCircleOne(),
  'number circle seven': PhosphorIcons.numberCircleSeven(),
  'number circle six': PhosphorIcons.numberCircleSix(),
  'number circle three': PhosphorIcons.numberCircleThree(),
  'number circle two': PhosphorIcons.numberCircleTwo(),
  'number circle zero': PhosphorIcons.numberCircleZero(),
  'number eight': PhosphorIcons.numberEight(),
  'number five': PhosphorIcons.numberFive(),
  'number four': PhosphorIcons.numberFour(),
  'number nine': PhosphorIcons.numberNine(),
  'number one': PhosphorIcons.numberOne(),
  'number seven': PhosphorIcons.numberSeven(),
  'number six': PhosphorIcons.numberSix(),
  'number square eight': PhosphorIcons.numberSquareEight(),
  'number square five': PhosphorIcons.numberSquareFive(),
  'number square four': PhosphorIcons.numberSquareFour(),
  'number square nine': PhosphorIcons.numberSquareNine(),
  'number square one': PhosphorIcons.numberSquareOne(),
  'number square seven': PhosphorIcons.numberSquareSeven(),
  'number square six': PhosphorIcons.numberSquareSix(),
  'number square three': PhosphorIcons.numberSquareThree(),
  'number square two': PhosphorIcons.numberSquareTwo(),
  'number square zero': PhosphorIcons.numberSquareZero(),
  'number three': PhosphorIcons.numberThree(),
  'number two': PhosphorIcons.numberTwo(),
  'number zero': PhosphorIcons.numberZero(),
  'numpad': PhosphorIcons.numpad(),
  'nut': PhosphorIcons.nut(),
  'ny times logo': PhosphorIcons.nyTimesLogo(),
  'octagon': PhosphorIcons.octagon(),
  'office chair': PhosphorIcons.officeChair(),
  'onigiri': PhosphorIcons.onigiri(),
  'open ai logo': PhosphorIcons.openAiLogo(),
  'option': PhosphorIcons.option(),
  'orange': PhosphorIcons.orange(),
  'orange slice': PhosphorIcons.orangeSlice(),
  'oven': PhosphorIcons.oven(),
  'package': PhosphorIcons.package(),
  'paint brush': PhosphorIcons.paintBrush(),
  'paint brush broad': PhosphorIcons.paintBrushBroad(),
  'paint brush household': PhosphorIcons.paintBrushHousehold(),
  'paint bucket': PhosphorIcons.paintBucket(),
  'paint roller': PhosphorIcons.paintRoller(),
  'palette': PhosphorIcons.palette(),
  'panorama': PhosphorIcons.panorama(),
  'pants': PhosphorIcons.pants(),
  'paper plane': PhosphorIcons.paperPlane(),
  'paper plane right': PhosphorIcons.paperPlaneRight(),
  'paper plane tilt': PhosphorIcons.paperPlaneTilt(),
  'paperclip': PhosphorIcons.paperclip(),
  'paperclip horizontal': PhosphorIcons.paperclipHorizontal(),
  'parachute': PhosphorIcons.parachute(),
  'paragraph': PhosphorIcons.paragraph(),
  'parallelogram': PhosphorIcons.parallelogram(),
  'park': PhosphorIcons.park(),
  'password': PhosphorIcons.password(),
  'path': PhosphorIcons.path(),
  'patreon logo': PhosphorIcons.patreonLogo(),
  'pause': PhosphorIcons.pause(),
  'pause circle': PhosphorIcons.pauseCircle(),
  'paw print': PhosphorIcons.pawPrint(),
  'paypal logo': PhosphorIcons.paypalLogo(),
  'peace': PhosphorIcons.peace(),
  'pen': PhosphorIcons.pen(),
  'pen nib': PhosphorIcons.penNib(),
  'pen nib straight': PhosphorIcons.penNibStraight(),
  'pencil': PhosphorIcons.pencil(),
  'pencil circle': PhosphorIcons.pencilCircle(),
  'pencil line': PhosphorIcons.pencilLine(),
  'pencil ruler': PhosphorIcons.pencilRuler(),
  'pencil simple': PhosphorIcons.pencilSimple(),
  'pencil simple line': PhosphorIcons.pencilSimpleLine(),
  'pencil simple slash': PhosphorIcons.pencilSimpleSlash(),
  'pencil slash': PhosphorIcons.pencilSlash(),
  'pentagon': PhosphorIcons.pentagon(),
  'pentagram': PhosphorIcons.pentagram(),
  'pepper': PhosphorIcons.pepper(),
  'percent': PhosphorIcons.percent(),
  'person': PhosphorIcons.person(),
  'person arms spread': PhosphorIcons.personArmsSpread(),
  'person simple': PhosphorIcons.personSimple(),
  'person simple bike': PhosphorIcons.personSimpleBike(),
  'person simple circle': PhosphorIcons.personSimpleCircle(),
  'person simple hike': PhosphorIcons.personSimpleHike(),
  'person simple run': PhosphorIcons.personSimpleRun(),
  'person simple ski': PhosphorIcons.personSimpleSki(),
  'person simple snowboard': PhosphorIcons.personSimpleSnowboard(),
  'person simple swim': PhosphorIcons.personSimpleSwim(),
  'person simple tai chi': PhosphorIcons.personSimpleTaiChi(),
  'person simple throw': PhosphorIcons.personSimpleThrow(),
  'person simple walk': PhosphorIcons.personSimpleWalk(),
  'perspective': PhosphorIcons.perspective(),
  'phone': PhosphorIcons.phone(),
  'phone call': PhosphorIcons.phoneCall(),
  'phone disconnect': PhosphorIcons.phoneDisconnect(),
  'phone incoming': PhosphorIcons.phoneIncoming(),
  'phone list': PhosphorIcons.phoneList(),
  'phone outgoing': PhosphorIcons.phoneOutgoing(),
  'phone pause': PhosphorIcons.phonePause(),
  'phone plus': PhosphorIcons.phonePlus(),
  'phone slash': PhosphorIcons.phoneSlash(),
  'phone transfer': PhosphorIcons.phoneTransfer(),
  'phone x': PhosphorIcons.phoneX(),
  'phosphor logo': PhosphorIcons.phosphorLogo(),
  'pi': PhosphorIcons.pi(),
  'piano keys': PhosphorIcons.pianoKeys(),
  'picnic table': PhosphorIcons.picnicTable(),
  'piggy bank': PhosphorIcons.piggyBank(),
  'pill': PhosphorIcons.pill(),
  'ping pong': PhosphorIcons.pingPong(),
  'pint glass': PhosphorIcons.pintGlass(),
  'pinterest logo': PhosphorIcons.pinterestLogo(),
  'pinwheel': PhosphorIcons.pinwheel(),
  'pipe': PhosphorIcons.pipe(),
  'pipe wrench': PhosphorIcons.pipeWrench(),
  'pix logo': PhosphorIcons.pixLogo(),
  'pizza': PhosphorIcons.pizza(),
  'placeholder': PhosphorIcons.placeholder(),
  'planet': PhosphorIcons.planet(),
  'plant': PhosphorIcons.plant(),
  'play': PhosphorIcons.play(),
  'play circle': PhosphorIcons.playCircle(),
  'play pause': PhosphorIcons.playPause(),
  'playlist': PhosphorIcons.playlist(),
  'plug': PhosphorIcons.plug(),
  'plug charging': PhosphorIcons.plugCharging(),
  'plugs': PhosphorIcons.plugs(),
  'plugs connected': PhosphorIcons.plugsConnected(),
  'plus': PhosphorIcons.plus(),
  'plus circle': PhosphorIcons.plusCircle(),
  'plus minus': PhosphorIcons.plusMinus(),
  'plus square': PhosphorIcons.plusSquare(),
  'poker chip': PhosphorIcons.pokerChip(),
  'police car': PhosphorIcons.policeCar(),
  'polygon': PhosphorIcons.polygon(),
  'popcorn': PhosphorIcons.popcorn(),
  'popsicle': PhosphorIcons.popsicle(),
  'potted plant': PhosphorIcons.pottedPlant(),
  'power': PhosphorIcons.power(),
  'prescription': PhosphorIcons.prescription(),
  'presentation': PhosphorIcons.presentation(),
  'presentation chart': PhosphorIcons.presentationChart(),
  'printer': PhosphorIcons.printer(),
  'prohibit': PhosphorIcons.prohibit(),
  'prohibit inset': PhosphorIcons.prohibitInset(),
  'projector screen': PhosphorIcons.projectorScreen(),
  'projector screen chart': PhosphorIcons.projectorScreenChart(),
  'pulse': PhosphorIcons.pulse(),
  'push pin': PhosphorIcons.pushPin(),
  'push pin simple': PhosphorIcons.pushPinSimple(),
  'push pin simple slash': PhosphorIcons.pushPinSimpleSlash(),
  'push pin slash': PhosphorIcons.pushPinSlash(),
  'puzzle piece': PhosphorIcons.puzzlePiece(),
  'qr code': PhosphorIcons.qrCode(),
  'question': PhosphorIcons.question(),
  'question mark': PhosphorIcons.questionMark(),
  'queue': PhosphorIcons.queue(),
  'quotes': PhosphorIcons.quotes(),
  'rabbit': PhosphorIcons.rabbit(),
  'racquet': PhosphorIcons.racquet(),
  'radical': PhosphorIcons.radical(),
  'radio': PhosphorIcons.radio(),
  'radio button': PhosphorIcons.radioButton(),
  'radioactive': PhosphorIcons.radioactive(),
  'rainbow': PhosphorIcons.rainbow(),
  'rainbow cloud': PhosphorIcons.rainbowCloud(),
  'ranking': PhosphorIcons.ranking(),
  'read cv logo': PhosphorIcons.readCvLogo(),
  'receipt': PhosphorIcons.receipt(),
  'receipt x': PhosphorIcons.receiptX(),
  'record': PhosphorIcons.record(),
  'rectangle': PhosphorIcons.rectangle(),
  'rectangle dashed': PhosphorIcons.rectangleDashed(),
  'recycle': PhosphorIcons.recycle(),
  'reddit logo': PhosphorIcons.redditLogo(),
  'repeat': PhosphorIcons.repeat(),
  'repeat once': PhosphorIcons.repeatOnce(),
  'replit logo': PhosphorIcons.replitLogo(),
  'resize': PhosphorIcons.resize(),
  'rewind': PhosphorIcons.rewind(),
  'rewind circle': PhosphorIcons.rewindCircle(),
  'road horizon': PhosphorIcons.roadHorizon(),
  'robot': PhosphorIcons.robot(),
  'rocket': PhosphorIcons.rocket(),
  'rocket launch': PhosphorIcons.rocketLaunch(),
  'rows': PhosphorIcons.rows(),
  'rows plus bottom': PhosphorIcons.rowsPlusBottom(),
  'rows plus top': PhosphorIcons.rowsPlusTop(),
  'rss': PhosphorIcons.rss(),
  'rss simple': PhosphorIcons.rssSimple(),
  'rug': PhosphorIcons.rug(),
  'ruler': PhosphorIcons.ruler(),
  'sailboat': PhosphorIcons.sailboat(),
  'scales': PhosphorIcons.scales(),
  'scan': PhosphorIcons.scan(),
  'scan smiley': PhosphorIcons.scanSmiley(),
  'scissors': PhosphorIcons.scissors(),
  'scooter': PhosphorIcons.scooter(),
  'screencast': PhosphorIcons.screencast(),
  'screwdriver': PhosphorIcons.screwdriver(),
  'scribble': PhosphorIcons.scribble(),
  'scribble loop': PhosphorIcons.scribbleLoop(),
  'scroll': PhosphorIcons.scroll(),
  'seal': PhosphorIcons.seal(),
  'seal check': PhosphorIcons.sealCheck(),
  'seal percent': PhosphorIcons.sealPercent(),
  'seal question': PhosphorIcons.sealQuestion(),
  'seal warning': PhosphorIcons.sealWarning(),
  'seat': PhosphorIcons.seat(),
  'seatbelt': PhosphorIcons.seatbelt(),
  'security camera': PhosphorIcons.securityCamera(),
  'selection': PhosphorIcons.selection(),
  'selection all': PhosphorIcons.selectionAll(),
  'selection background': PhosphorIcons.selectionBackground(),
  'selection foreground': PhosphorIcons.selectionForeground(),
  'selection inverse': PhosphorIcons.selectionInverse(),
  'selection plus': PhosphorIcons.selectionPlus(),
  'selection slash': PhosphorIcons.selectionSlash(),
  'shapes': PhosphorIcons.shapes(),
  'share': PhosphorIcons.share(),
  'share fat': PhosphorIcons.shareFat(),
  'share network': PhosphorIcons.shareNetwork(),
  'shield': PhosphorIcons.shield(),
  'shield check': PhosphorIcons.shieldCheck(),
  'shield checkered': PhosphorIcons.shieldCheckered(),
  'shield chevron': PhosphorIcons.shieldChevron(),
  'shield plus': PhosphorIcons.shieldPlus(),
  'shield slash': PhosphorIcons.shieldSlash(),
  'shield star': PhosphorIcons.shieldStar(),
  'shield warning': PhosphorIcons.shieldWarning(),
  'shipping container': PhosphorIcons.shippingContainer(),
  'shirt folded': PhosphorIcons.shirtFolded(),
  'shooting star': PhosphorIcons.shootingStar(),
  'shopping bag': PhosphorIcons.shoppingBag(),
  'shopping bag open': PhosphorIcons.shoppingBagOpen(),
  'shopping cart': PhosphorIcons.shoppingCart(),
  'shopping cart simple': PhosphorIcons.shoppingCartSimple(),
  'shovel': PhosphorIcons.shovel(),
  'shower': PhosphorIcons.shower(),
  'shrimp': PhosphorIcons.shrimp(),
  'shuffle': PhosphorIcons.shuffle(),
  'shuffle angular': PhosphorIcons.shuffleAngular(),
  'shuffle simple': PhosphorIcons.shuffleSimple(),
  'sidebar': PhosphorIcons.sidebar(),
  'sidebar simple': PhosphorIcons.sidebarSimple(),
  'sigma': PhosphorIcons.sigma(),
  'sign in': PhosphorIcons.signIn(),
  'sign out': PhosphorIcons.signOut(),
  'signature': PhosphorIcons.signature(),
  'signpost': PhosphorIcons.signpost(),
  'sim card': PhosphorIcons.simCard(),
  'siren': PhosphorIcons.siren(),
  'sketch logo': PhosphorIcons.sketchLogo(),
  'skip back': PhosphorIcons.skipBack(),
  'skip back circle': PhosphorIcons.skipBackCircle(),
  'skip forward': PhosphorIcons.skipForward(),
  'skip forward circle': PhosphorIcons.skipForwardCircle(),
  'skull': PhosphorIcons.skull(),
  'skype logo': PhosphorIcons.skypeLogo(),
  'slack logo': PhosphorIcons.slackLogo(),
  'sliders': PhosphorIcons.sliders(),
  'sliders horizontal': PhosphorIcons.slidersHorizontal(),
  'slideshow': PhosphorIcons.slideshow(),
  'smiley': PhosphorIcons.smiley(),
  'smiley angry': PhosphorIcons.smileyAngry(),
  'smiley blank': PhosphorIcons.smileyBlank(),
  'smiley meh': PhosphorIcons.smileyMeh(),
  'smiley melting': PhosphorIcons.smileyMelting(),
  'smiley nervous': PhosphorIcons.smileyNervous(),
  'smiley sad': PhosphorIcons.smileySad(),
  'smiley sticker': PhosphorIcons.smileySticker(),
  'smiley wink': PhosphorIcons.smileyWink(),
  'smiley x eyes': PhosphorIcons.smileyXEyes(),
  'snapchat logo': PhosphorIcons.snapchatLogo(),
  'sneaker': PhosphorIcons.sneaker(),
  'sneaker move': PhosphorIcons.sneakerMove(),
  'snowflake': PhosphorIcons.snowflake(),
  'soccer ball': PhosphorIcons.soccerBall(),
  'sock': PhosphorIcons.sock(),
  'solar panel': PhosphorIcons.solarPanel(),
  'solar roof': PhosphorIcons.solarRoof(),
  'sort ascending': PhosphorIcons.sortAscending(),
  'sort descending': PhosphorIcons.sortDescending(),
  'soundcloud logo': PhosphorIcons.soundcloudLogo(),
  'spade': PhosphorIcons.spade(),
  'sparkle': PhosphorIcons.sparkle(),
  'speaker hifi': PhosphorIcons.speakerHifi(),
  'speaker high': PhosphorIcons.speakerHigh(),
  'speaker low': PhosphorIcons.speakerLow(),
  'speaker none': PhosphorIcons.speakerNone(),
  'speaker simple high': PhosphorIcons.speakerSimpleHigh(),
  'speaker simple low': PhosphorIcons.speakerSimpleLow(),
  'speaker simple none': PhosphorIcons.speakerSimpleNone(),
  'speaker simple slash': PhosphorIcons.speakerSimpleSlash(),
  'speaker simple x': PhosphorIcons.speakerSimpleX(),
  'speaker slash': PhosphorIcons.speakerSlash(),
  'speaker x': PhosphorIcons.speakerX(),
  'speedometer': PhosphorIcons.speedometer(),
  'sphere': PhosphorIcons.sphere(),
  'spinner': PhosphorIcons.spinner(),
  'spinner ball': PhosphorIcons.spinnerBall(),
  'spinner gap': PhosphorIcons.spinnerGap(),
  'spiral': PhosphorIcons.spiral(),
  'split horizontal': PhosphorIcons.splitHorizontal(),
  'split vertical': PhosphorIcons.splitVertical(),
  'spotify logo': PhosphorIcons.spotifyLogo(),
  'spray bottle': PhosphorIcons.sprayBottle(),
  'square': PhosphorIcons.square(),
  'square half': PhosphorIcons.squareHalf(),
  'square half bottom': PhosphorIcons.squareHalfBottom(),
  'square logo': PhosphorIcons.squareLogo(),
  'square split horizontal': PhosphorIcons.squareSplitHorizontal(),
  'square split vertical': PhosphorIcons.squareSplitVertical(),
  'squares four': PhosphorIcons.squaresFour(),
  'stack': PhosphorIcons.stack(),
  'stack minus': PhosphorIcons.stackMinus(),
  'stack overflow logo': PhosphorIcons.stackOverflowLogo(),
  'stack plus': PhosphorIcons.stackPlus(),
  'stack simple': PhosphorIcons.stackSimple(),
  'stairs': PhosphorIcons.stairs(),
  'stamp': PhosphorIcons.stamp(),
  'standard definition': PhosphorIcons.standardDefinition(),
  'star': PhosphorIcons.star(),
  'star and crescent': PhosphorIcons.starAndCrescent(),
  'star four': PhosphorIcons.starFour(),
  'star half': PhosphorIcons.starHalf(),
  'star of david': PhosphorIcons.starOfDavid(),
  'steam logo': PhosphorIcons.steamLogo(),
  'steering wheel': PhosphorIcons.steeringWheel(),
  'steps': PhosphorIcons.steps(),
  'stethoscope': PhosphorIcons.stethoscope(),
  'sticker': PhosphorIcons.sticker(),
  'stool': PhosphorIcons.stool(),
  'stop': PhosphorIcons.stop(),
  'stop circle': PhosphorIcons.stopCircle(),
  'storefront': PhosphorIcons.storefront(),
  'strategy': PhosphorIcons.strategy(),
  'stripe logo': PhosphorIcons.stripeLogo(),
  'student': PhosphorIcons.student(),
  'subset of': PhosphorIcons.subsetOf(),
  'subset proper of': PhosphorIcons.subsetProperOf(),
  'subtitles': PhosphorIcons.subtitles(),
  'subtitles slash': PhosphorIcons.subtitlesSlash(),
  'subtract': PhosphorIcons.subtract(),
  'subtract square': PhosphorIcons.subtractSquare(),
  'subway': PhosphorIcons.subway(),
  'suitcase': PhosphorIcons.suitcase(),
  'suitcase rolling': PhosphorIcons.suitcaseRolling(),
  'suitcase simple': PhosphorIcons.suitcaseSimple(),
  'sun': PhosphorIcons.sun(),
  'sun dim': PhosphorIcons.sunDim(),
  'sun horizon': PhosphorIcons.sunHorizon(),
  'sunglasses': PhosphorIcons.sunglasses(),
  'superset of': PhosphorIcons.supersetOf(),
  'superset proper of': PhosphorIcons.supersetProperOf(),
  'swap': PhosphorIcons.swap(),
  'swatches': PhosphorIcons.swatches(),
  'swimming pool': PhosphorIcons.swimmingPool(),
  'sword': PhosphorIcons.sword(),
  'synagogue': PhosphorIcons.synagogue(),
  'syringe': PhosphorIcons.syringe(),
  't shirt': PhosphorIcons.tShirt(),
  'table': PhosphorIcons.table(),
  'tabs': PhosphorIcons.tabs(),
  'tag': PhosphorIcons.tag(),
  'tag chevron': PhosphorIcons.tagChevron(),
  'tag simple': PhosphorIcons.tagSimple(),
  'target': PhosphorIcons.target(),
  'taxi': PhosphorIcons.taxi(),
  'tea bag': PhosphorIcons.teaBag(),
  'telegram logo': PhosphorIcons.telegramLogo(),
  'television': PhosphorIcons.television(),
  'television simple': PhosphorIcons.televisionSimple(),
  'tennis ball': PhosphorIcons.tennisBall(),
  'tent': PhosphorIcons.tent(),
  'terminal': PhosphorIcons.terminal(),
  'terminal window': PhosphorIcons.terminalWindow(),
  'test tube': PhosphorIcons.testTube(),
  'text a underline': PhosphorIcons.textAUnderline(),
  'text aa': PhosphorIcons.textAa(),
  'text align center': PhosphorIcons.textAlignCenter(),
  'text align justify': PhosphorIcons.textAlignJustify(),
  'text align left': PhosphorIcons.textAlignLeft(),
  'text align right': PhosphorIcons.textAlignRight(),
  'text b': PhosphorIcons.textB(),
  'text columns': PhosphorIcons.textColumns(),
  'text h': PhosphorIcons.textH(),
  'text h five': PhosphorIcons.textHFive(),
  'text h four': PhosphorIcons.textHFour(),
  'text h one': PhosphorIcons.textHOne(),
  'text h six': PhosphorIcons.textHSix(),
  'text h three': PhosphorIcons.textHThree(),
  'text h two': PhosphorIcons.textHTwo(),
  'text indent': PhosphorIcons.textIndent(),
  'text italic': PhosphorIcons.textItalic(),
  'text outdent': PhosphorIcons.textOutdent(),
  'text strikethrough': PhosphorIcons.textStrikethrough(),
  'text subscript': PhosphorIcons.textSubscript(),
  'text superscript': PhosphorIcons.textSuperscript(),
  'text t': PhosphorIcons.textT(),
  'text t slash': PhosphorIcons.textTSlash(),
  'text underline': PhosphorIcons.textUnderline(),
  'textbox': PhosphorIcons.textbox(),
  'thermometer': PhosphorIcons.thermometer(),
  'thermometer cold': PhosphorIcons.thermometerCold(),
  'thermometer hot': PhosphorIcons.thermometerHot(),
  'thermometer simple': PhosphorIcons.thermometerSimple(),
  'threads logo': PhosphorIcons.threadsLogo(),
  'three d': PhosphorIcons.threeD(),
  'thumbs down': PhosphorIcons.thumbsDown(),
  'thumbs up': PhosphorIcons.thumbsUp(),
  'ticket': PhosphorIcons.ticket(),
  'tidal logo': PhosphorIcons.tidalLogo(),
  'tiktok logo': PhosphorIcons.tiktokLogo(),
  'tilde': PhosphorIcons.tilde(),
  'timer': PhosphorIcons.timer(),
  'tip jar': PhosphorIcons.tipJar(),
  'tipi': PhosphorIcons.tipi(),
  'tire': PhosphorIcons.tire(),
  'toggle left': PhosphorIcons.toggleLeft(),
  'toggle right': PhosphorIcons.toggleRight(),
  'toilet': PhosphorIcons.toilet(),
  'toilet paper': PhosphorIcons.toiletPaper(),
  'toolbox': PhosphorIcons.toolbox(),
  'tooth': PhosphorIcons.tooth(),
  'tornado': PhosphorIcons.tornado(),
  'tote': PhosphorIcons.tote(),
  'tote simple': PhosphorIcons.toteSimple(),
  'towel': PhosphorIcons.towel(),
  'tractor': PhosphorIcons.tractor(),
  'trademark': PhosphorIcons.trademark(),
  'trademark registered': PhosphorIcons.trademarkRegistered(),
  'traffic cone': PhosphorIcons.trafficCone(),
  'traffic sign': PhosphorIcons.trafficSign(),
  'traffic signal': PhosphorIcons.trafficSignal(),
  'train': PhosphorIcons.train(),
  'train regional': PhosphorIcons.trainRegional(),
  'train simple': PhosphorIcons.trainSimple(),
  'tram': PhosphorIcons.tram(),
  'translate': PhosphorIcons.translate(),
  'trash': PhosphorIcons.trash(),
  'trash simple': PhosphorIcons.trashSimple(),
  'tray': PhosphorIcons.tray(),
  'tray arrow down': PhosphorIcons.trayArrowDown(),
  'tray arrow up': PhosphorIcons.trayArrowUp(),
  'treasure chest': PhosphorIcons.treasureChest(),
  'tree': PhosphorIcons.tree(),
  'tree evergreen': PhosphorIcons.treeEvergreen(),
  'tree palm': PhosphorIcons.treePalm(),
  'tree structure': PhosphorIcons.treeStructure(),
  'tree view': PhosphorIcons.treeView(),
  'trend down': PhosphorIcons.trendDown(),
  'trend up': PhosphorIcons.trendUp(),
  'triangle': PhosphorIcons.triangle(),
  'triangle dashed': PhosphorIcons.triangleDashed(),
  'trolley': PhosphorIcons.trolley(),
  'trolley suitcase': PhosphorIcons.trolleySuitcase(),
  'trophy': PhosphorIcons.trophy(),
  'truck': PhosphorIcons.truck(),
  'truck trailer': PhosphorIcons.truckTrailer(),
  'tumblr logo': PhosphorIcons.tumblrLogo(),
  'twitch logo': PhosphorIcons.twitchLogo(),
  'twitter logo': PhosphorIcons.twitterLogo(),
  'umbrella': PhosphorIcons.umbrella(),
  'umbrella simple': PhosphorIcons.umbrellaSimple(),
  'union': PhosphorIcons.union(),
  'unite': PhosphorIcons.unite(),
  'unite square': PhosphorIcons.uniteSquare(),
  'upload': PhosphorIcons.upload(),
  'upload simple': PhosphorIcons.uploadSimple(),
  'usb': PhosphorIcons.usb(),
  'user': PhosphorIcons.user(),
  'user check': PhosphorIcons.userCheck(),
  'user circle': PhosphorIcons.userCircle(),
  'user circle check': PhosphorIcons.userCircleCheck(),
  'user circle dashed': PhosphorIcons.userCircleDashed(),
  'user circle gear': PhosphorIcons.userCircleGear(),
  'user circle minus': PhosphorIcons.userCircleMinus(),
  'user circle plus': PhosphorIcons.userCirclePlus(),
  'user focus': PhosphorIcons.userFocus(),
  'user gear': PhosphorIcons.userGear(),
  'user list': PhosphorIcons.userList(),
  'user minus': PhosphorIcons.userMinus(),
  'user plus': PhosphorIcons.userPlus(),
  'user rectangle': PhosphorIcons.userRectangle(),
  'user sound': PhosphorIcons.userSound(),
  'user square': PhosphorIcons.userSquare(),
  'user switch': PhosphorIcons.userSwitch(),
  'users': PhosphorIcons.users(),
  'users four': PhosphorIcons.usersFour(),
  'users three': PhosphorIcons.usersThree(),
  'van': PhosphorIcons.van(),
  'vault': PhosphorIcons.vault(),
  'vector three': PhosphorIcons.vectorThree(),
  'vector two': PhosphorIcons.vectorTwo(),
  'vibrate': PhosphorIcons.vibrate(),
  'video': PhosphorIcons.video(),
  'video camera': PhosphorIcons.videoCamera(),
  'video camera slash': PhosphorIcons.videoCameraSlash(),
  'video conference': PhosphorIcons.videoConference(),
  'vignette': PhosphorIcons.vignette(),
  'vinyl record': PhosphorIcons.vinylRecord(),
  'virtual reality': PhosphorIcons.virtualReality(),
  'virus': PhosphorIcons.virus(),
  'visor': PhosphorIcons.visor(),
  'voicemail': PhosphorIcons.voicemail(),
  'volleyball': PhosphorIcons.volleyball(),
  'wall': PhosphorIcons.wall(),
  'wallet': PhosphorIcons.wallet(),
  'warehouse': PhosphorIcons.warehouse(),
  'warning': PhosphorIcons.warning(),
  'warning circle': PhosphorIcons.warningCircle(),
  'warning diamond': PhosphorIcons.warningDiamond(),
  'warning octagon': PhosphorIcons.warningOctagon(),
  'washing machine': PhosphorIcons.washingMachine(),
  'watch': PhosphorIcons.watch(),
  'wave sawtooth': PhosphorIcons.waveSawtooth(),
  'wave sine': PhosphorIcons.waveSine(),
  'wave square': PhosphorIcons.waveSquare(),
  'wave triangle': PhosphorIcons.waveTriangle(),
  'waveform': PhosphorIcons.waveform(),
  'waveform slash': PhosphorIcons.waveformSlash(),
  'waves': PhosphorIcons.waves(),
  'webcam': PhosphorIcons.webcam(),
  'webcam slash': PhosphorIcons.webcamSlash(),
  'webhooks logo': PhosphorIcons.webhooksLogo(),
  'wechat logo': PhosphorIcons.wechatLogo(),
  'whatsapp logo': PhosphorIcons.whatsappLogo(),
  'wheelchair': PhosphorIcons.wheelchair(),
  'wheelchair motion': PhosphorIcons.wheelchairMotion(),
  'wifi high': PhosphorIcons.wifiHigh(),
  'wifi low': PhosphorIcons.wifiLow(),
  'wifi medium': PhosphorIcons.wifiMedium(),
  'wifi none': PhosphorIcons.wifiNone(),
  'wifi slash': PhosphorIcons.wifiSlash(),
  'wifi x': PhosphorIcons.wifiX(),
  'wind': PhosphorIcons.wind(),
  'windmill': PhosphorIcons.windmill(),
  'windows logo': PhosphorIcons.windowsLogo(),
  'wine': PhosphorIcons.wine(),
  'wrench': PhosphorIcons.wrench(),
  'x': PhosphorIcons.x(),
  'x circle': PhosphorIcons.xCircle(),
  'x logo': PhosphorIcons.xLogo(),
  'x square': PhosphorIcons.xSquare(),
  'yarn': PhosphorIcons.yarn(),
  'yin yang': PhosphorIcons.yinYang(),
  'youtube logo': PhosphorIcons.youtubeLogo(),
};
