// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:trosko/models/category/category.dart';
import 'package:trosko/models/hive_adapters.dart';
import 'package:trosko/models/settings/settings.dart';
import 'package:trosko/models/transaction/transaction.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    // registerAdapter(ColorAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(TransactionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    // registerAdapter(ColorAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(TransactionAdapter());
  }
}
