// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYNfXJ-II_yz964vptgtOxzWu8ifCdeXQ',
    appId: '1:64667044702:web:fc5488f03ac84c54671dcf',
    messagingSenderId: '64667044702',
    projectId: 'trosko-2f982',
    authDomain: 'trosko-2f982.firebaseapp.com',
    storageBucket: 'trosko-2f982.firebasestorage.app',
    measurementId: 'G-QJTD12F29D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjdeB-0aM-K2pCUkA3KxY3gNa8ZaPUPnE',
    appId: '1:64667044702:android:be9d2cbdcb1ca3f8671dcf',
    messagingSenderId: '64667044702',
    projectId: 'trosko-2f982',
    storageBucket: 'trosko-2f982.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfXhIfFRfzPunGN5MZO4Qlez64RFzHIPY',
    appId: '1:64667044702:ios:713702ee60e8c9ce671dcf',
    messagingSenderId: '64667044702',
    projectId: 'trosko-2f982',
    storageBucket: 'trosko-2f982.firebasestorage.app',
    iosBundleId: 'com.josipkilic.trosko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfXhIfFRfzPunGN5MZO4Qlez64RFzHIPY',
    appId: '1:64667044702:ios:713702ee60e8c9ce671dcf',
    messagingSenderId: '64667044702',
    projectId: 'trosko-2f982',
    storageBucket: 'trosko-2f982.firebasestorage.app',
    iosBundleId: 'com.josipkilic.trosko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYNfXJ-II_yz964vptgtOxzWu8ifCdeXQ',
    appId: '1:64667044702:web:1d831fef07469b49671dcf',
    messagingSenderId: '64667044702',
    projectId: 'trosko-2f982',
    authDomain: 'trosko-2f982.firebaseapp.com',
    storageBucket: 'trosko-2f982.firebasestorage.app',
    measurementId: 'G-145TW5TJFC',
  );
}
